Project import generated by Copybara.
GitOrigin-RevId: 5f83cfb30fd6b74f5675da748e65fae86a018a67

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-set -e
-
 check_and_install() {
 	command -v "$1" >/dev/null 2>&1 || {
 		if command -v apt-get >/dev/null 2>&1; then
@@ -20,40 +18,61 @@ check_and_install() {
 		fi
 	}
 }
-check_and_install curl curl
-check_and_install sudo sudo
 
-install_pkgx() {
-	os_type=$(uname)
-	arch_type=$(uname -m)
+mise_version=v2025.9.17
+mise_install_path="$HOME/.local/bin/mise"
 
-	if [ "$os_type" = "Linux" ]; then
-		if [ "$arch_type" = "x86_64" ]; then
-			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+linux+x86-64.tar.xz
-		elif [ "$arch_type" = "aarch64" ]; then
-			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+linux+aarch64.tar.xz
-		else
-			echo "Unsupported architecture: $arch_type"
-			exit 1
-		fi
-	elif [ "$os_type" = "Darwin" ]; then
-		if [ "$arch_type" = "x86_64" ]; then
-			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+darwin+x86-64.tar.xz
-		elif [ "$arch_type" = "arm64" ] || [ "$arch_type" = "aarch64" ]; then
-			curl -L -o pkgx.tar.xz https://github.com/pkgxdev/pkgx/releases/download/v1.3.1/pkgx-1.3.1+darwin+aarch64.tar.xz
-		else
-			echo "Unsupported architecture: $arch_type"
-			exit 1
-		fi
+install_mise() {
+	set -e
+
+	# Ensure curl is installed
+	check_and_install curl curl
+
+	echo "Installing Mise version $mise_version at $mise_install_path..."
+	curl "https://mise.run" | MISE_INSTALL_PATH=$mise_install_path MISE_VERSION=$mise_version sh
+	echo "Mise installation completed."
+
+	set +e
+}
+
+setup_mise() {
+	# Recursively trust all projects in the monorepo by finding mise.toml and running `mise trust` in each directory
+	echo "Trusting all projects in the monorepo..."
+	find . -type f -name ".mise.toml" -execdir "$mise_install_path" trust -y . \;
+
+	echo "Installing default tools..."
+	$mise_install_path install
+
+	echo "Mise setup completed."
+}
+
+activate_mise() {
+	# Detect if the script is being sourced (so we can activate mise in the current shell).
+	# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced/28776166#28776166
+	if [ -n "$BASH_VERSION" ]; then
+		[ "$0" != "$BASH_SOURCE" ] && sourced=1 || sourced=0
 	else
-		echo "Unsupported OS type: $os_type"
-		exit 1
+		case ${0##*/} in sh|-sh|dash|-dash) sourced=1 ;; *) sourced=0 ;; esac
 	fi
 
-	tar -xf pkgx.tar.xz
-	sudo install -m 755 pkgx /usr/local/bin
-	rm -f pkgx.tar.xz pkgx
+	if [ "$sourced" -eq 1 ]; then
+		echo "Activating Mise in the current shell..."
+		eval "$("$mise_install_path" activate --shims)"
+		echo "Mise is now active in this shell."
+	else
+		echo "Could not activate Mise because this script was run as a normal command."
+		echo "To activate Mise in the current shell, run:"
+		echo "    . $0"
+		echo "Alternatively, consult 'mise activate --help' for more options."
+	fi
 }
-command -v pkgx >/dev/null || install_pkgx
-command -v nu >/dev/null || pkgx install nushell.sh@0.96.1
-command -v just >/dev/null || pkgx install just.systems@1.29.1
+
+if [ ! -x "$mise_install_path" ]; then
+	echo "Mise not found. Starting installation and setup..."
+	install_mise
+	setup_mise
+	activate_mise
+else
+	echo "Mise is already installed at $mise_install_path."
+	activate_mise
+fi
